baseURL = "http://thenatureofsoftware.se/"
languageCode = "sv-se"
title = "The Nature of Software"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-89872233-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  github = "https://github.com/thenatureofsoftware"
  twitter = "https://twitter.com/thenatureofsoft"
  instagram = "https://www.instagram.com/thenatureofsoftware/"
  youtube = "https://www.youtube.com/channel/UCucUjFaWiPIDWqmZUVf76Aw"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  featured_image = "/images/strykjarnet.jpg"
